name: Configure Azure environment

on:
  issues:
    types: [closed]

env:
  AZURE_RESOURCE_GROUP: probot-applications
  AZURE_APP_PLAN: prod-probot-apps
  AZURE_LOCATION: '"Central US"'
  AZURE_WEBAPP_NAME: probot-add-collaborators

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name, 'provision probot app')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resource group
        if: success()
        run: |
          az group create --location ${{env.AZURE_LOCATION}} --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Create Azure app service plan
        if: success()
        run: |
          az appservice plan create --resource-group ${{env.AZURE_RESOURCE_GROUP}} --name ${{env.AZURE_APP_PLAN}} --is-linux --sku F1 --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Create webapp resource
        if: success()
        run: |
          az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_WEBAPP_NAME }}  --deployment-container-image-name nginx --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

#       - name: Set Web App secrets
#         if: success()
#         uses: Azure/appservice-settings@v1
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           app-settings-json: |
#             [
#                 {
#                     "name": "APP_ID",
#                     "value": "${{secrets.PROBOT_APP_ID}}",
#                     "slotSetting": false
#                 },
#                 {
#                     "name": "PRIVATE_KEY",
#                     "value": "${{secrets.PROBOT_APP_PRI_KEY}}",
#                     "slotSetting": false
#                 },
#                 {
#                     "name": "WEBHOOK_SECRET",
#                     "value": "${{secrets.PROBOT_WEBHOOK_SECRET}}",
#                     "slotSetting": false
#                 }
#             ]

      - name: use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install deps
        run: |
          npm install

      - name: Deploy application
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: "probot-add-collaborators"
